from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel('Customer', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('name', models.CharField(max_length=200)),
            ('company', models.CharField(blank=True, max_length=200)),
            ('phone', models.CharField(blank=True, max_length=30)),
            ('email', models.EmailField(blank=True)),
            ('address_line1', models.CharField(blank=True, max_length=255)),
            ('address_line2', models.CharField(blank=True, max_length=255)),
            ('city', models.CharField(blank=True, max_length=100)),
            ('state', models.CharField(blank=True, max_length=100)),
            ('pincode', models.CharField(blank=True, max_length=10)),
            ('delivery_address', models.TextField(blank=True)),
            ('notes', models.TextField(blank=True)),
            ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to='auth.user')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel('Project', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('reference', models.CharField(max_length=50, unique=True)),
            ('name', models.CharField(max_length=200)),
            ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.customer')),
            ('status', models.CharField(choices=[('draft','Draft'),('survey','Survey Pending'),('quoted','Quoted'),('ordered','Order Confirmed'),('production','In Production'),('delivered','Delivered'),('installed','Installed'),('locked','Locked'),('cancelled','Cancelled')], default='draft', max_length=20)),
            ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_sales', to='auth.user')),
            ('site_address', models.TextField(blank=True)),
            ('survey_date', models.DateField(blank=True, null=True)),
            ('survey_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_surveyed', to='auth.user')),
            ('production_date', models.DateField(blank=True, null=True)),
            ('delivery_date', models.DateField(blank=True, null=True)),
            ('notes', models.TextField(blank=True)),
            ('internal_notes', models.TextField(blank=True)),
            ('is_locked', models.BooleanField(default=False)),
            ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_locked', to='auth.user')),
            ('locked_at', models.DateTimeField(blank=True, null=True)),
            ('lock_reason', models.CharField(blank=True, max_length=255)),
            ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to='auth.user')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel('ProjectStatusHistory', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='projects.project')),
            ('from_status', models.CharField(blank=True, max_length=20)),
            ('to_status', models.CharField(max_length=20)),
            ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ('notes', models.CharField(blank=True, max_length=255)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel('MeasurementItem', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='projects.project')),
            ('line_no', models.CharField(max_length=10)),
            ('reference', models.CharField(max_length=20)),
            ('location', models.CharField(max_length=100)),
            ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurement_items', to='catalog.system')),
            ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color')),
            ('glass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.glass')),
            ('width', models.IntegerField()),
            ('height', models.IntegerField()),
            ('qty', models.PositiveIntegerField(default=1)),
            ('description', models.CharField(blank=True, max_length=255)),
            ('n_panels', models.PositiveSmallIntegerField(default=1)),
            ('hinge_side', models.CharField(blank=True, choices=[('L','Left'),('R','Right'),('','N/A')], max_length=5)),
            ('opening_angles', models.CharField(blank=True, max_length=50)),
            ('flyscreen', models.BooleanField(default=False)),
            ('drainage', models.BooleanField(default=False)),
            ('is_toughened', models.BooleanField(default=False)),
            ('surveyed_from', models.CharField(blank=True, choices=[('inside','Inside'),('outside','Outside')], max_length=10)),
            ('notes', models.TextField(blank=True)),
            ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ('final_width', models.IntegerField(blank=True, null=True)),
            ('final_height', models.IntegerField(blank=True, null=True)),
            ('dimensions_confirmed', models.BooleanField(default=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ], options={'ordering': ['sort_order', 'line_no']}),
    ]
