# Generated by Django 5.0.4 on 2026-06-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='height',
            field=models.IntegerField(help_text='mm'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='line_no',
            field=models.CharField(help_text='e.g. 0001', max_length=10),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='location',
            field=models.CharField(help_text='e.g. Living Room', max_length=100),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='reference',
            field=models.CharField(help_text='e.g. W1, D1', max_length=20),
        ),
        migrations.AlterField(
            model_name='measurementitem',
            name='width',
            field=models.IntegerField(help_text='mm'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='projectstatushistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
