from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('projects', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel('ProductionJob', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='projects.project')),
            ('job_no', models.CharField(max_length=30, unique=True)),
            ('status', models.CharField(choices=[('pending','Pending'),('in_progress','In Progress'),('optimized','Optimized'),('cutting','Cutting'),('assembly','Assembly'),('qc','Quality Check'),('complete','Complete')], default='pending', max_length=20)),
            ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs', to='auth.user')),
            ('scheduled_date', models.DateField(blank=True, null=True)),
            ('completed_date', models.DateField(blank=True, null=True)),
            ('notes', models.TextField(blank=True)),
            ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_jobs_created', to='auth.user')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel('ProductionItem', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.productionjob')),
            ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.measurementitem')),
            ('line_no', models.CharField(max_length=10)),
            ('reference', models.CharField(blank=True, max_length=20)),
            ('location', models.CharField(blank=True, max_length=100)),
            ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.system')),
            ('glass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.glass')),
            ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color')),
            ('width', models.IntegerField()),
            ('height', models.IntegerField()),
            ('qty', models.PositiveIntegerField(default=1)),
            ('n_panels', models.PositiveSmallIntegerField(default=1)),
            ('description', models.CharField(blank=True, max_length=255)),
            ('notes', models.TextField(blank=True)),
            ('is_complete', models.BooleanField(default=False)),
            ('sort_order', models.PositiveSmallIntegerField(default=0)),
        ], options={'ordering': ['sort_order', 'line_no']}),
        migrations.CreateModel('ProductionCutItem', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('production_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_items', to='production.productionitem')),
            ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.profile')),
            ('position', models.CharField(max_length=50)),
            ('cut_length_mm', models.IntegerField()),
            ('left_angle', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('right_angle', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('quantity', models.PositiveSmallIntegerField(default=1)),
            ('position_code', models.CharField(blank=True, max_length=20)),
        ], options={'ordering': ['profile__category', 'position']}),
        migrations.CreateModel('HardwareRequirement', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('production_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_items', to='production.productionitem')),
            ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.hardware')),
            ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ('unit', models.CharField(default='pcs', max_length=20)),
            ('notes', models.CharField(blank=True, max_length=200)),
        ]),
        migrations.CreateModel('OptimizationRun', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('production_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='production.productionjob')),
            ('run_date', models.DateTimeField(auto_now_add=True)),
            ('bar_length_mm', models.IntegerField(default=6000)),
            ('kerf_mm', models.IntegerField(default=5)),
            ('end_waste_mm', models.IntegerField(default=10)),
            ('min_reusable_mm', models.IntegerField(default=300)),
            ('total_bars_used', models.IntegerField(default=0)),
            ('total_material_mm', models.IntegerField(default=0)),
            ('total_cut_mm', models.IntegerField(default=0)),
            ('total_waste_mm', models.IntegerField(default=0)),
            ('utilisation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ('is_active', models.BooleanField(default=True)),
            ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.user')),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ], options={'ordering': ['-created_at']}),
        migrations.CreateModel('OptimizationSegment', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('optimization_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='production.optimizationrun')),
            ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.profile')),
            ('bars_required', models.IntegerField(default=0)),
            ('bar_length_mm', models.IntegerField(default=6000)),
            ('total_cut_length_mm', models.IntegerField(default=0)),
            ('waste_mm', models.IntegerField(default=0)),
            ('offcut_mm', models.IntegerField(default=0)),
            ('total_pieces', models.IntegerField(default=0)),
        ], options={'ordering': ['profile__category', 'profile__stock_no']}),
        migrations.CreateModel('OptimizedCut', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='production.optimizationsegment')),
            ('production_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionitem')),
            ('bar_number', models.PositiveSmallIntegerField()),
            ('cut_length_mm', models.IntegerField()),
            ('left_angle', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('right_angle', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('position_code', models.CharField(blank=True, max_length=20)),
            ('start_position_mm', models.IntegerField(default=0)),
        ], options={'ordering': ['bar_number', 'start_position_mm']}),
        migrations.CreateModel('ReusableOffcut', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.profile')),
            ('length_mm', models.IntegerField()),
            ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offcuts_generated', to='production.productionjob')),
            ('used_in_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offcuts_used', to='production.productionjob')),
            ('is_available', models.BooleanField(default=True)),
            ('location_notes', models.CharField(blank=True, max_length=200)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ], options={'ordering': ['-length_mm']}),
    ]
