# Generated by Django 5.0.4 on 2026-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionitem',
            name='diagnostics',
            field=models.TextField(blank=True, help_text='System warnings or formula diagnostics for this item'),
        ),
        migrations.AlterField(
            model_name='hardwarerequirement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one active run per job at a time'),
        ),
        migrations.AlterField(
            model_name='optimizationsegment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optimizedcut',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productioncutitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productioncutitem',
            name='position',
            field=models.CharField(help_text='formula position key', max_length=50),
        ),
        migrations.AlterField(
            model_name='productioncutitem',
            name='position_code',
            field=models.CharField(blank=True, help_text='e.g. F^A, S<B2', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productionjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reusableoffcut',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reusableoffcut',
            name='location_notes',
            field=models.CharField(blank=True, help_text='Rack/shelf location', max_length=200),
        ),
    ]
