from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel('Brand', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('name', models.CharField(max_length=100, unique=True)),
            ('description', models.TextField(blank=True)),
            ('is_active', models.BooleanField(default=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ]),
        migrations.CreateModel('Color', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('name', models.CharField(max_length=100)),
            ('code', models.CharField(blank=True, max_length=20)),
            ('is_active', models.BooleanField(default=True)),
        ]),
        migrations.CreateModel('System', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('code', models.CharField(max_length=20, unique=True)),
            ('name', models.CharField(max_length=150)),
            ('category', models.CharField(max_length=30, choices=[('casement','Casement'),('sliding','Sliding'),('fixed','Fixed'),('door_swing','Swing Door'),('door_sliding','Sliding Door'),('louver','Louver'),('composite','Composite')])),
            ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ('description', models.TextField(blank=True)),
            ('is_active', models.BooleanField(default=True)),
            ('sort_order', models.PositiveSmallIntegerField(default=0)),
        ], options={'ordering': ['sort_order', 'code']}),
        migrations.CreateModel('Profile', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('stock_no', models.CharField(max_length=30, unique=True)),
            ('name', models.CharField(max_length=150)),
            ('category', models.CharField(max_length=30, choices=[('outer_frame','Outer Frame'),('sash','Sash'),('transom','Transom'),('mullion','Mullion'),('bead','Glass Bead'),('slider_frame','Slider Frame'),('slider_sash','Slider Sash'),('reinforcement','Reinforcement'),('gasket','Gasket'),('ancillary','Ancillary')])),
            ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='catalog.system')),
            ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ('description', models.TextField(blank=True)),
            ('weight_per_meter', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ('cost_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ('standard_bar_length', models.IntegerField(default=6000)),
            ('offset_left', models.IntegerField(default=0)),
            ('offset_right', models.IntegerField(default=0)),
            ('offset_top', models.IntegerField(default=0)),
            ('offset_bottom', models.IntegerField(default=0)),
            ('default_left_angle', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('default_right_angle', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('is_active', models.BooleanField(default=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ], options={'ordering': ['category', 'stock_no']}),
        migrations.CreateModel('ProfileFormula', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='catalog.profile')),
            ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_formulas', to='catalog.system')),
            ('position', models.CharField(max_length=50)),
            ('formula', models.CharField(max_length=255)),
            ('cut_angle_left', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('cut_angle_right', models.DecimalField(decimal_places=1, default=90, max_digits=5)),
            ('quantity_formula', models.CharField(default='1', max_length=100)),
            ('notes', models.CharField(blank=True, max_length=255)),
            ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ('is_active', models.BooleanField(default=True)),
        ], options={'ordering': ['system', 'sort_order'],
                   'unique_together': {('profile', 'system', 'position')}}),
        migrations.CreateModel('Glass', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('code', models.CharField(max_length=30, unique=True)),
            ('name', models.CharField(max_length=150)),
            ('specification', models.CharField(max_length=20, choices=[('clear','Clear'),('tinted','Tinted'),('frosted','Frosted'),('toughened','Toughened'),('laminated','Laminated'),('dgu','DGU (Double Glazed)'),('low_e','Low-E'),('reflective','Reflective')])),
            ('thickness', models.CharField(max_length=30)),
            ('cost_per_sqft', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ('cost_per_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ('weight_per_sqm', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
            ('is_toughened', models.BooleanField(default=False)),
            ('is_active', models.BooleanField(default=True)),
            ('notes', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ], options={'ordering': ['specification', 'name'], 'verbose_name_plural': 'Glasses'}),
        migrations.CreateModel('Hardware', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('stock_no', models.CharField(max_length=30, unique=True)),
            ('name', models.CharField(max_length=150)),
            ('category', models.CharField(max_length=20, choices=[('hinge','Hinge'),('handle','Handle'),('lock','Lock & Espag'),('roller','Roller'),('gasket','Gasket'),('screw','Screw & Fastener'),('accessory','Accessory'),('installation','Installation Material')])),
            ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.brand')),
            ('unit', models.CharField(default='pcs', max_length=20)),
            ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ('weight_per_unit', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
            ('is_active', models.BooleanField(default=True)),
            ('notes', models.TextField(blank=True)),
            ('created_at', models.DateTimeField(auto_now_add=True)),
        ], options={'ordering': ['category', 'stock_no']}),
        migrations.CreateModel('SystemHardwareRule', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_rules', to='catalog.system')),
            ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.hardware')),
            ('quantity_formula', models.CharField(default='1', max_length=100)),
            ('notes', models.CharField(blank=True, max_length=200)),
            ('is_active', models.BooleanField(default=True)),
        ], options={'unique_together': {('system', 'hardware')}}),
        migrations.CreateModel('CompanySettings', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True)),
            ('company_name', models.CharField(default='CutFlow Fenestration', max_length=200)),
            ('address_line1', models.CharField(blank=True, max_length=200)),
            ('address_line2', models.CharField(blank=True, max_length=200)),
            ('city', models.CharField(blank=True, max_length=100)),
            ('state', models.CharField(blank=True, max_length=100)),
            ('pincode', models.CharField(blank=True, max_length=10)),
            ('phone', models.CharField(blank=True, max_length=30)),
            ('email', models.EmailField(blank=True)),
            ('website', models.URLField(blank=True)),
            ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
            ('gst_no', models.CharField(blank=True, max_length=20)),
            ('sgst_rate', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
            ('cgst_rate', models.DecimalField(decimal_places=2, default=9, max_digits=5)),
            ('igst_rate', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
            ('quotation_validity_days', models.IntegerField(default=30)),
            ('default_payment_terms', models.TextField(default='50% advance, balance before delivery.')),
            ('quotation_terms', models.TextField(blank=True)),
            ('default_bar_length_mm', models.IntegerField(default=6000)),
            ('kerf_mm', models.IntegerField(default=5)),
            ('end_waste_mm', models.IntegerField(default=10)),
            ('min_reusable_offcut_mm', models.IntegerField(default=300)),
            ('updated_at', models.DateTimeField(auto_now=True)),
        ], options={'verbose_name': 'Company Settings', 'verbose_name_plural': 'Company Settings'}),
    ]
