# Generated by Django 5.0.4 on 2026-06-01 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileformula',
            options={'ordering': ['system', 'profile__category', 'sort_order']},
        ),
        migrations.RenameField(
            model_name='profileformula',
            old_name='notes',
            new_name='remarks',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='fabrication_rate_per_meter',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Fabrication cost per running metre', max_digits=10),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='material_wastage_percent',
            field=models.DecimalField(decimal_places=2, default=8, help_text='Default material wastage percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='profit_margin_percent',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Default profit margin percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='profileformula',
            name='formula_type',
            field=models.CharField(choices=[('cut', 'Cut'), ('quantity', 'Quantity'), ('glass', 'Glass'), ('hardware', 'Hardware'), ('other', 'Other')], default='cut', max_length=20),
        ),
        migrations.AddField(
            model_name='profileformula',
            name='max_height',
            field=models.IntegerField(blank=True, help_text='Maximum H to apply formula', null=True),
        ),
        migrations.AddField(
            model_name='profileformula',
            name='max_width',
            field=models.IntegerField(blank=True, help_text='Maximum W to apply formula', null=True),
        ),
        migrations.AddField(
            model_name='profileformula',
            name='min_height',
            field=models.IntegerField(blank=True, help_text='Minimum H to apply formula', null=True),
        ),
        migrations.AddField(
            model_name='profileformula',
            name='min_width',
            field=models.IntegerField(blank=True, help_text='Minimum W to apply formula', null=True),
        ),
        migrations.AddField(
            model_name='profileformula',
            name='panel_condition',
            field=models.CharField(blank=True, help_text='Optional boolean condition using W, H, n_panels', max_length=255),
        ),
        migrations.AddField(
            model_name='system',
            name='budget_markup_percent',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Budget system markup %', max_digits=5),
        ),
        migrations.AddField(
            model_name='system',
            name='markup_percent',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Standard system markup %', max_digits=5),
        ),
        migrations.AddField(
            model_name='system',
            name='premium_markup_percent',
            field=models.DecimalField(decimal_places=2, default=25, help_text='Premium system markup %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=models.CharField(blank=True, help_text='RAL or hex code', max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='glass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='glass',
            name='thickness',
            field=models.CharField(help_text='e.g. 5-10-6 or 6mm', max_length=30),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='unit',
            field=models.CharField(default='pcs', help_text='pcs / m / set', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cost_per_meter',
            field=models.DecimalField(decimal_places=2, default=0, help_text='INR per metre', max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offset_bottom',
            field=models.IntegerField(default=0, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offset_left',
            field=models.IntegerField(default=0, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offset_right',
            field=models.IntegerField(default=0, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='offset_top',
            field=models.IntegerField(default=0, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='standard_bar_length',
            field=models.IntegerField(default=6000, help_text='mm'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight_per_meter',
            field=models.DecimalField(decimal_places=4, default=0, help_text='kg/m', max_digits=8),
        ),
        migrations.AlterField(
            model_name='profileformula',
            name='formula',
            field=models.CharField(help_text='Expression using W, H, offset_l, offset_r, offset_t, offset_b, n_panels', max_length=255),
        ),
        migrations.AlterField(
            model_name='profileformula',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profileformula',
            name='position',
            field=models.CharField(help_text='e.g. frame_width, frame_height, sash_width', max_length=50),
        ),
        migrations.AlterField(
            model_name='profileformula',
            name='quantity_formula',
            field=models.CharField(default='1', help_text='Expression for piece count, e.g. 2 or n_panels*2', max_length=100),
        ),
        migrations.AlterField(
            model_name='system',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemhardwarerule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemhardwarerule',
            name='quantity_formula',
            field=models.CharField(default='1', help_text='Expression using n_panels, n_sashes, qty', max_length=100),
        ),
        migrations.CreateModel(
            name='SystemProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('outer_frame_top', 'Outer Frame Top'), ('outer_frame_bottom', 'Outer Frame Bottom'), ('outer_frame_left', 'Outer Frame Left'), ('outer_frame_right', 'Outer Frame Right'), ('shutter_vertical', 'Shutter Vertical'), ('shutter_horizontal', 'Shutter Horizontal'), ('interlock', 'Interlock'), ('bead_horizontal', 'Bead Horizontal'), ('bead_vertical', 'Bead Vertical'), ('ancillary', 'Ancillary')], max_length=40)),
                ('formula_group', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_profiles', to='catalog.profile')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_profiles', to='catalog.system')),
            ],
            options={
                'ordering': ['system', 'sort_order', 'role', 'profile__stock_no'],
                'unique_together': {('system', 'profile', 'role')},
            },
        ),
        migrations.AddField(
            model_name='profileformula',
            name='system_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='catalog.systemprofile'),
        ),
    ]
