# Generated by Django 5.0.4 on 2026-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seed_system_profile_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprofile',
            name='role',
            field=models.CharField(choices=[('outer_frame_top', 'Outer Frame Top'), ('outer_frame_bottom', 'Outer Frame Bottom'), ('outer_frame_left', 'Outer Frame Left'), ('outer_frame_right', 'Outer Frame Right'), ('shutter_vertical', 'Shutter Vertical'), ('shutter_horizontal', 'Shutter Horizontal'), ('interlock', 'Interlock'), ('mullion', 'Mullion'), ('track', 'Track'), ('bead_horizontal', 'Bead Horizontal'), ('bead_vertical', 'Bead Vertical'), ('ancillary', 'Ancillary')], max_length=40),
        ),
    ]
