# Generated by Django 5.0.4 on 2026-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_quotation_pricing_variant_alter_quotation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quote_type',
            field=models.CharField(choices=[('tentative', 'Tentative'), ('production', 'Production')], default='tentative', help_text='Quotation intent: tentative estimate or production-ready quote', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='pricing_variant',
            field=models.CharField(choices=[('budget', 'Budget'), ('economy', 'Economy'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', help_text='Apply pricing variant to item markups', max_length=20),
        ),
    ]
